apiVersion: apps/v1
kind: Deployment
metadata:
  name: siva-deployment
  labels:
    app: siva
spec:
  replicas: 2
  selector:
    matchLabels:
      app: siva
  template:
    metadata:
      labels:
        app: siva
    spec:
      containers:
      - name: siva-container
        image: 779679300583.dkr.ecr.ap-south-1.amazonaws.com/siva-ecr-repository02:siva
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: siva-service
spec:
  type: LoadBalancer
  selector:
    app: siva
  ports:
    - protocol: TCP
      port: 8080        # External port
      targetPort: 8080  # Container port
